############################################################
#
# article静态化微服务
# web访问端口号  约定：8002
#
############################################################
server:
  # port: 8002
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml配置文件中的环境配置 dev：开发环境；test：测试环境；prod：生产环境
  application:
    name: service-article-html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://root:root@10.18.185.191:27017
      database: xunmiwe-news
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates

# 定义freemarker生成的html路径位置
freemarker:
  html:
    target: /Users/wuxunmin/IdeaProjects/freemarker_hml
    article: /Users/wuxunmin/Downloads/apache-tomcat-9.0.60/webapps/imooc-news/portal/a