############################################################
#
# 用户微服务
# web访问端口号  约定：8003
#
############################################################
server:
  # port: 8003
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml配置文件中的环境配置 dev：开发环境；test：测试环境；prod：生产环境
  application:
    name: service-user
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-news-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: la178944
    hikari:
      connection-timeout: 30000   # 等待连接池分配连接的最大时长
      minimum-idle: 5             # 最小连接数
      maximum-pool-size: 20       # 最大连接数
      auto-commit: true           # 自动提交
      idle-timeout: 600000        # 连接超时的最大时长
      pool-name: DataSourceHikariCP   # 连接池名字
      max-lifetime: 1800000       # 连接的生命时长
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: localhost
    port: 5672
    username: xunmiw
    password: la178944
    virtual-host: xunmiwe-news
  cloud:
    stream:
      bindings:                           # 绑定通道和交换机
        mqOutput:                         # 定义生产者的通道
          destination: streamExchange     # 自定义交换机名称
        mqInput:                          # 定义消费者的通道
          destination: streamExchange
          group: girls
  zipkin:
    base-url: http://10.18.185.191:9411/
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  data:
    elasticsearch:
      cluster-name: xunmiwe-elasticsearch
      cluster-nodes: 10.18.185.191:9300

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.xunmiw.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.xunmiw.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

############################################################
#
# Eureka client配置信息
#
############################################################
eureka:
  server:
    hostname: localhost
    port: 7001
  client:
    register-with-eureka: true    # 将该服务注册到Eureka
    fetch-registry: true          # 从Eureka拉取服务
    service-url:
#      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/    # Eureka注册中心的服务地址
      defaultZone: http://eureka-cluster-7002:7002/eureka/,http://eureka-cluster-7003:7003/eureka/,http://eureka-cluster-7004:7004/eureka/    # Eureka集群地址

# 配置Hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000     # 设置Hystrix超时时间，超过5s触发降级
      circuitBreaker:                       # 配置断路器
        enabled: true
        requestVolumeThreshold: 10          # 触发熔断最小请求次数，默认20
        sleepWindowInMilliseconds: 15000    # 熔断后过几秒后尝试半开状态
        errorThresholdPercentage: 50        # 触发熔断的异常率，默认50