############################################################
#
# 分布式搜索服务
# web访问端口号  约定：8006
#
############################################################
server:
  port: 8006
  tomcat:
    uri-encoding: UTF-8

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: service-search